# Generated by Django 5.0.7 on 2024-08-22 13:57

import django.db.models.deletion
import shop.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'), models.Index(fields=['description'], name='shop_catego_descrip_f0fcf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to=shop.helpers.SaveMedia.save_book_image_path)),
                ('count', models.IntegerField(default=0)),
                ('colors', models.CharField(max_length=200)),
                ('sizes', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC')], default='PUBLIC', max_length=15)),
                ('shipping_days', models.IntegerField(default=0)),
                ('shipping_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.quality')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='shop_shop_name_ff50b8_idx')],
            },
        ),
    ]
