# Generated by Django 5.0.7 on 2024-08-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sizes',
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
