# Generated by Django 5.0.7 on 2024-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_colors_remove_shop_sizes_shop_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='size',
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.ManyToManyField(to='shop.color'),
        ),
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
