# Generated by Django 5.0.7 on 2024-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_color_size_remove_shop_color_remove_shop_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('Qora', 'Qora'), ('Oq', 'Oq'), ('Qizil', 'Qizil'), ('Kok', 'Kok'), ('Yashil', 'Yashil')], max_length=50),
        ),
    ]
